### ISSUE TITLE
gx publish on windows does not work with subdirectories

### ISSUE THREAD

**Issue by slothbag** [whyrusleeping/gx#39]
It appears gx does not detect windows sub directories when adding a package. The name contains the directory. e.g. css\style.css instead of css being an actual directory.

**Comment by whyrusleeping** [comment]
should be fixed in #40 thanks for reporting!

**Comment by whyrusleeping** [comment]
@slothbag is this still an issue?

**Comment by slothbag** [comment]
Yup, still an issue.  currently its causing some sort of race condition in IPFS (latest build for windows).. So I can't even tell if the folder structure is correct.

Unfortunately I cant get a stack trace.. it kills my computer.

**Comment by slothbag** [comment]
The good news is `gx publish` is not causing race condition in IPFS anymore.

But this issue with windows not creating the subdirectories correctly is still a critical bug for me.
